### ISSUE TITLE
Export a file of all interactions

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#447] opened 2015-03-26 09:46 UTC
It would be good to export a file of all interactions in Chado alongside the PHAF and GAF files for each release.  This could be in the format of the file we send to BioGRID.

Original comment by: kimrutherford

**Comment by ValWood** [comment] 2016-10-18 19:45
If anyone asks we have the "high quality interactions file" that we use for EsyN....
We can think more about this later

**Comment by ValWood** [comment] 2024-11-22 08:55
closing as duplicate of
https://github.com/pombase/pombase-chado/issues/411

**Closed by ValWood** 2024-11-22 08:55 UTC
Labels: sourceforge, auto-migrated, eventually, export files, future
