### ISSUE TITLE
Some of the curation attribution is wrong bug

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#761] opened 2020-02-29 13:59 UTC
For example, I did this one but it has  Sophie

<img width="941" alt="Screenshot 2020-02-29 at 14 06 04" src="https://user-images.githubusercontent.com/7359272/75608996-b9948c00-5afc-11ea-9fe2-0d2c3e9bd43d.png">

I saw this one first which was Matthew Swaffer a minute ago, but now its's also Sophie
https://www.pombase.org/reference/PMID:25720772
<img width="1015" alt="Screenshot 2020-02-29 at 13 58 16" src="https://user-images.githubusercontent.com/7359272/75608899-a1703d00-5afb-11ea-9e45-1d24ff304153.png">

It's really odd but these are curators from papers I looked at earlier. So it seem that the  page is updated but not the attribution?

**Comment by kimrutherford** [comment] 2020-03-02 09:36
That's very weird!  I don't know how that could happen.  It looks like it's fixed now so it's hard to debug.  Maybe the load and re-release last night cured the problem.  If you see it again I'll investigate straight away.

https://www.pombase.org/reference/PMID:23697806
https://www.pombase.org/reference/PMID:25720772

**Comment by ValWood** [comment] 2020-03-02 15:10
I can only tell you that I was looking throught he list of the most highly accessed papers in Google Analytics. Many of these are HTP screens so it would be a big load on the database I guess that I accessed about 20 of these HTP one after the other?

**Comment by kimrutherford** [comment] 2020-03-02 20:03
OK thanks.  It's possible things were just lagging beside.  I'll try that and see if I can reproduce it.

**Comment by kimrutherford** [comment] 2020-03-03 07:36
> It's possible things were just lagging

It was a bug.  The curator name wasn't always being updated.  In particular if you were looking at a community curated paper and then went to a non-community one the community curator name wasn't cleared.

Fixed now.

**Closed by kimrutherford** 2020-03-03 07:36 UTC
Labels: bug

**Comment by ValWood** [comment] 2020-03-03 09:32
well tracked down!

**Comment by kimrutherford** [comment] 2020-03-03 09:52
> well tracked down!

It's one of my most common bugs.  I've caused and fixed similar problems several times now.  :-)
