### ISSUE TITLE
unknown alleles which are later named should pick up the new name (pcn1 example)

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#531] opened 2016-03-11 12:15 UTC
3 Nice examples here:
![names](https://cloud.githubusercontent.com/assets/7359272/13701850/7913dfb0-e782-11e5-89d6-641360b5c2a0.jpg)

unnamed (L2V, R64A)    -> pcn1-26 (L2V, R64A)
unnamed R64A  ->  pcn1-26  R64A 
unnamed L2V  ->  pcn1-1 L2V

I presume the unnamed allele was added first and the name was added subsequently. However, I thought the new name would override in Canto ? Maybe one example here comes from a PHAF file?

**Comment by kimrutherford** [comment] 2016-03-13 20:33
In the current code, if there is an allele in Chado with a name and then we try to load another allele with the same description and no name, they are merged.  Unfortunately, if it's the other way around - the unnamed allele is in Chado then we try to load another allele with the same description that has a name, they aren't merged so we end up with two copies.

Maybe that's what's happening here?

**Comment by ValWood** [comment] 2016-03-14 09:37
It sounds like it. Maybe we can make it so if a name is added for an unnamed allele it supedcedes 'unnamed'?

**Comment by kimrutherford** [comment] 2016-05-10 20:26
From Midori - this might be caused by the fix above:

There are bunch of warnings in the latest Canto log
(log.2016-05-06-09-59-16.curation-tool-data-load-output) like:

warning in 84d34826e72c8725: allele_type for new allele "tsn1+(wild_type)"
does not match the existing allele with the same name "tsn1+(deletion)"
(from session 84d34826e72c8725)

and
warning in f5dc7dbed1ca7c42: allele_type for new allele
"cds1delta(deletion)" does not match the existing allele with the same
name "cds1delta(wild_type)" (from session e464a50ec363f029)

I looked at the sessions in the examples above, and I can't see where
Canto or the Chado loader is getting the notion that there's anything with
a name like yfg1+ but a deletion type/description. Something's going awry.

**Closed** 2016-05-14 22:33 UTC
Labels: high priority, QC, syntax_check
