### ISSUE TITLE
"can't find genotype details" warnings

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#470] opened 2015-08-04 11:31 UTC
Since the big multi-allele advance, the export_warnings logs have been chock-a-block with warnings that it "can't find details for: [some genotype]", e.g. 

can't find details for: 2ef9911b1699da5e-genotype-4 (id: 147441)
can't find details for: 2ef9911b1699da5e-genotype-3 (id: 147439)
can't find details for: PomBase-genotype-11745 (id: 128113)
can't find details for: PomBase-genotype-11744 (id: 128111)

Apparently (per email) this is unexpected and therefore ticket-worthy.

**Comment by mah11** [comment] 2015-08-04 14:37
might also be related to the worryingly small pombase-build-2015-08-01-v1-l1.phaf.gz - only 60K / 6043 lines
(sf. v53 release PHAF 587K)

**Comment by mah11** [comment] 2015-08-05 10:16
related to #465?

**Comment by kimrutherford** [comment] 2015-08-05 10:18
Yep, it's the same problem I think.

**Comment by kimrutherford** [comment] 2015-08-06 03:45
This is happening because the annotation is now attached to the genotype instead of alleles in Chado.  I can fix that for the single allele genotype caused by changing the code a bit.

But we haven't talked about how to store the multi-allele genotypes in the PHAF file.  I think we talked about having two files, one with the details of genotype name, ID etc. and the alleles for each genotype.  And another with the phenotype annotation that mentions genotype identifiers but not alleles.  A bit like GPAD/GPI?  I think there was a document or wiki page about it, but I can't find it.

Should we export single-allele genotype/phenotypes for now while we work out a better plan?

**Comment by kimrutherford** [comment] 2015-08-06 06:16
GPAD/GPI ticket: #276

**Comment by mah11** [comment] 2015-08-06 09:38
The wiki page is https://curation.pombase.org/pombase-trac/wiki/PhenotypeImportExportFormats (it hasn't been substantially updated in a long time, but I suppose we haven't really changed our thinking much; we've just left it on the proverbial back burner). We've been tossing around the idea of three files for bulk import of multi-allele phenotypes: one for allele descriptions, one to link alleles and genotypes, and one to link genotypes and phenotypes. The envisioned formats have been tab-delimited rather than stanza-based (ala GPAD/GPI) but the big idea is similar.

I'm not sure if we decided whether to use the three-file setup for export as well as import. The alternative would be stuffing a genotype description into what is now the allele description, which would be a bugger to parse (technical term). But will users get their heads round putting three files together? I don't know.

In the meantime, I'm entirely willing to export just the single allele phenotypes into the PHAF, and include something explanatory and apologetic in the v54 announcement. Better than delaying the release, methinks.

For testing bulk loading, there are three little dummy files in pombe-embl/external_data/phaf_files/in-progress/ - the ones with multigene*.tsv names.

phew ... that turned long. :P

**Comment by kimrutherford** [comment] 2015-08-06 10:11
> In the meantime, I'm entirely willing to export just the single allele phenotypes into the PHAF

Sounds good.  I'll do that.

**Comment by kimrutherford** [comment] 2015-08-10 07:30
Should be fixed now.  I've run the export code on the Chado from yesterday and it looked OK.  There is a new load running now.

**Comment by mah11** [comment] 2015-08-10 15:16
It's looking much metter as of the latest :)
(10-Aug-2015 log.2015-08-10-05-35-16.export_warnings)

**Closed** 2015-08-11 05:22 UTC
Labels: high priority, next
