### ISSUE TITLE
Canto GO annotations missing from GAF?

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#595] opened 2016-10-20 16:20 UTC
The GAF shrunk abruptly between pombase-build-2016-09-15 and pombase-build-2016-09-18 builds:

```
pombase-build-2016-09-11-v1.gaf.gz  2016-09-12 12:10    783K     [v61 release]
pombase-build-2016-09-15-v1.gaf.gz  2016-09-16 12:42    782K     
pombase-build-2016-09-18-v1.gaf.gz  2016-09-19 15:54    570K     
pombase-build-2016-10-17-v1.gaf.gz  2016-10-19 08:46    636K     [latest build as of ticket opening]
```

I noticed because annotations from PMID:15226425/d2288b20e67eb62d aren't in the latest GAF. Spot-checking a couple of other randomly chosen sessions, and a look at the latest gaf-load-output log, raises the ugly possibility that GO annotations aren't getting loaded from Canto. It doesn't look like a general Canto problem, though because the PHAFs have stayed at consistent sizes.

I added 'high priority' because something's going wrong, but I suppose you could change that because it'll be ages before the next release.

**Comment by ValWood** [comment] 2016-10-29 16:43
According to the current logs and GAF its the IEA data that isn't loading?
The Canto numbers look slightly higher in the logs.
If this is the case, this should get fixed when 
https://github.com/pombase/pombase-chado/issues/594
is implemented

**Comment by kimrutherford** [comment] 2016-10-30 08:51
I started looking at this last week but got distracted by fever.  It's very odd that there was a big drop and even odder that the gaf size seems to change quite a lot every load for the last month.  I'll look at this again first thing on Monday.

Recent file sizes:

    724K  pombase-build-2016-10-14-v1/pombase-build-2016-10-14-v1.gaf.gz
    624K  pombase-build-2016-10-15-v1/pombase-build-2016-10-15-v1.gaf.gz
    612K  pombase-build-2016-10-16-v1/pombase-build-2016-10-16-v1.gaf.gz
    640K  pombase-build-2016-10-17-v1/pombase-build-2016-10-17-v1.gaf.gz
    804K  pombase-build-2016-10-18-v1/pombase-build-2016-10-18-v1.gaf.gz
    676K  pombase-build-2016-10-22-v1/pombase-build-2016-10-22-v1.gaf.gz
    644K  pombase-build-2016-10-23-v1/pombase-build-2016-10-23-v1.gaf.gz
    608K  pombase-build-2016-10-24-v1/pombase-build-2016-10-24-v1.gaf.gz
    620K  pombase-build-2016-10-25-v1/pombase-build-2016-10-25-v1.gaf.gz
    664K  pombase-build-2016-10-26-v1/pombase-build-2016-10-26-v1.gaf.gz
    4.0K  pombase-build-2016-10-27-v1/pombase-build-2016-10-27-v1.gaf.gz
    664K  pombase-build-2016-10-28-v1/pombase-build-2016-10-28-v1.gaf.gz
    572K  pombase-build-2016-10-29-v1/pombase-build-2016-10-29-v1.gaf.gz

**Comment by ValWood** [comment] 2016-10-31 11:52
Yep it does seem to be quite random ;) fun!

**Comment by kimrutherford** [comment] 2016-11-06 23:34
Sorry it's taken so long to look at this.  The first thing I've noticed is that since 2016-09-18 there are no ND line in the GAF files.  I think that's probably a symptom not the cause.

**Comment by kimrutherford** [comment] 2016-11-07 07:16
I think I've tracked down the problem.  There was an error during the GAF file writing.  The error is in the log files but it was a bit buried so it was hard to spot.  The there were a few annotations from Canto that were stored incorrectly in Chado (see #597) which caused the GAF writer to fail.

The annotations were in:
   https://curation.pombase.org/pombe/curs/ccbd850b80722817/ro/

They were using FYPO:0003180 "decreased intergenic meiotic recombination" but that ID is now an alt_id for: FYPO:0002485.  That should be fine but the extension storing was going slightly wrong.  I've add #597 about the bug.

As a quick fix I've changed FYPO:0003180 to FYPO:0002485 in that session and I've started a new load.

I'll close this if that fixes things.

> there are no ND line in the GAF files

The ND lines are rewritten out at the end and the writer wasn't getting that far - the GAF files were truncated.

**Comment by kimrutherford** [comment] 2016-11-08 07:10
> As a quick fix I've changed FYPO:0003180 to FYPO:0002485 in that session and I've started a new load.

I forgot to check the other sessions.  Whoops.  I'll try again.

**Comment by kimrutherford** [comment] 2016-11-11 19:27
Fixed!

**Closed by kimrutherford** 2016-11-11 19:27 UTC
Labels: bug, GAF export, high priority

**Comment by ValWood** [comment] 2016-11-11 20:01
great thanks! Let me know  when  the stats page is next updated.

**Comment by kimrutherford** [comment] 2016-11-11 21:02
> Let me know when the stats page is next updated.

It's updated now.

**Comment by ValWood** [comment] 2016-11-11 21:15
thanks
