### ISSUE TITLE
export GAF file in a GO compliant way

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#744] opened 2019-09-18 15:57 UTC
Midori currently munges this file to  make it GO compliant.

@mah11  will list substitutions here

**Comment by mah11** [comment] 2019-09-23 13:49
- Delete all "negated" extensions (i.e. ones that use not_happens_during or not_exists_during).

- Do the substitutions in the attached script (basically just change a zillion relations to "has_input").

[munge_go_ext_rel.pl.txt](https://github.com/pombase/pombase-chado/files/3642408/munge_go_ext_rel.pl.txt)

note: remove spurious '.txt' file extension, added to make GitHub allow the upload

**Comment by mah11** [comment] 2020-08-04 12:49
Returning to this ticket again now that GO is seeking sign-off on the spec (linked above) ... there are two main points for us -- one is the relations between terms/IDs and gene products that GO now wants, and the other is submitting extensions with the small set of relations that GO now allows (where we've retained some more specific ones locally).

Term-gene product relations for GPAD column 3:

- For molecular function (F), use RO:0002327 'enables' (hideous usage, but it's what they've settled on) unless we have explicitly used contributes_to (RO:0002326).
- For biological process (P), ignore all the blather and just always use RO:0002331 'involved in'.
- For cellular component (C) it could be a bit tricky.
  - If we have used colocalizes_with anywhere, leave it (i.e. RO:0002325) as the relation, but I don't think we do use it any more.
  - For the rest, GO's preference depends on the term ancestry, so if this is realistically feasible:
    - if_descendant_of GO:0032991, use BFO:0000050 'part of'
    - otherwise, use RO:0001025 'located in'
   - If it would be a colossal pain in the ass to make this distinction, we could see if just using 'part of' (BFO:0000050) for all CC causes any ructions.

Extension relations (also noted for GAF in #744):

- Delete all "negated" extensions (i.e. ones that use not_happens_during or not_exists_during).
- Convert a whole bunch of relations to RO:0002233 (has input):
  - has_direct_input
  - regulates_activity_of
  - has_regulation_target
  - directly_negatively_regulates
  - directly_positively_regulates
- Convert occurs_at to BFO:0000066 (occurs in)
- I don't think we're using regulates_expression_of, regulates_transcription_of, or regulates_translation_of, but if we ever do, convert them to (wait for it) RO:0002233 (has input).

**Comment by mah11** [comment] 2020-08-04 12:55
If we do make GAFs for a while before switching to GPAD+GPI, the Qualifier column (col 4) should have the term-gp relations added - same as I listed for GPAD col 3 in the other ticket.

**Comment by ValWood** [comment] 2020-08-04 13:20
I vote we always make GAFS, I use them a lot.

and considering it took GO about 15 years to make this switch, I imagine that the community might be even longer piking it up... I wonder if anyone even remembers the reason to  do it ;).

**Comment by mah11** [comment] 2020-08-04 13:24
If we keep generating GAFs for ourselves and PomBase users, they'll be most useful if they *don't* meet GO's new specifications - in particular, we'll want to carry on using our more specific extension relations.

So how about if we
- start spawning GPAD+GPI for GO to collect; and
- stop sending them our GAF, and let them generate a GO-style GAF; and
- restore our local GAF to using what we want in extension relations?

That's still a few months away, but would mean Kim wouldn't have to do anything special for this ticket.

**Comment by ValWood** [comment] 2020-08-04 13:37
OK sounds good. I think we might occasionally need to use some of the "causally upstream " type relationships  for models, but we can cross that bridge when we come to it.

**Comment by kimrutherford** [comment] 2020-08-18 05:03
> I vote we always make GAFS, I use them a lot.

That make sense.

Sorry, long message follows:

The current GAF file that is processed by Midori and sent to GO is generated by Perl during the nightly load (it's here: https://curation.pombase.org/dumps/latest_build/).  The Perl script is slow to execute (15 minutes) and it's ugly.  I've been hoping to replace it with something better.  Thanks to the code for implementing pombase/website#949 we're close to being able to do that.

The new code for GAF download shares code with the GPAD/GPI export and it was easy to also export a file more or less in GAF format:
https://curation.pombase.org/dumps/latest_build/misc/pombase_style_gaf.tsv

The contents of that file is what you'd get if you query all genes in the query builder then exported as GAF from the dialog.  I think what you get is fine for users and probably for us.  But it's not what we need for submitting to GO. The problem is that the lines in the file very closely much what we show on the gene pages and have some tweaks that might not be appropriate for GO submission.  For example from pombase/website#108:

> display this "with" field information as an extension with the relationship "binds"

The GAF in the link above the GAF from the download dialog has binds() extensions rather than "with".  If we aren't sending it to GO that might not matter.  And for website users perhaps it's clearer if the GAF they download/export matches what they see on the gene pages.

So my suggestion is that we continue to export the GAF file for GO using the Perl code until we can switch over to submitting GPAD/GPI.  After that we can disable the Perl exporting and use the file generated by the new code as our main GAF file for users (and us).

**Comment by mah11** [comment] 2020-08-18 08:43
> ... long message ...
> So my suggestion is that we continue to export the GAF file for GO using the Perl code until we can switch over to submitting GPAD/GPI. After that we can disable the Perl exporting and use the file generated by the new code as our main GAF file for users (and us).

That makes a lot of sense to me. When we make te switch I'll add an entry to the FAQ to explain the difference between our GAF and what GO will have by then.

**Comment by ValWood** [comment] 2020-11-26 20:47
How much of this is still relevant?
Might be good to do  it with the GPAD stuff?

**Comment by kimrutherford** [comment] 2020-11-26 22:36
As I understand things, the new GPAD files more or less follow the GO rules.  I'm sure some tweaks will be needed though.

I think this issue is obsolete now.

I won't close it though until Midori has confirmed we should.

**Comment by mah11** [comment] 2020-11-27 11:46
Yeah, let's close this. It has been superseded by the plan to let GO get our annotations from our shiny new GPAD & GPI.

(I've made a note to self about documentation, for when they start generating GAFs from the GPADs they get; I'll do a ticket nearer the time.)

**Closed by mah11** 2020-11-27 11:46 UTC
Labels: GAF export, low priority
