### ISSUE TITLE
UniProt GO filtering possible problem

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#356] opened 2014-07-16 10:39 UTC
Recently we've noticed a couple of cases where a GO annotation should be filtered from the set we get from UniProt, but isn't.

What should happen: If there's an identical or more specific annotation*, only the one with "PomBase" as the source should be retained.

*i.e. citing same PMID and evidence; identical = the same GO term; more specific = we've used a term that's an is_a or part_of descendant of the one from UniProt

A couple examples where that isn't happening as desired:

a) A duplicate annotation is getting in for nbs1 (GO:0000723, IDA, PMID: 12944482) See [curation-tasks:#410] for more details.

b) We get this from UniProt:
PomBase SPBC16D10.04c   dna2        GO:0005657  PMID:22682245   IDA     C   DNA replication endonuclease-helicase Dna2      protein taxon:4896  20120727    UniProt 

but it should be filtered out because there's an IDA annotation to GO:0043596 from the Canto session (4aff66ed2ed54ace) for PMID:22682245, and GO:0043596 is_a GO:0005657.

PomBase SPBC16D10.04c   dna2        GO:0043596  PMID:22682245   IDA     C   DNA replication endonuclease-helicase Dna2      protein taxon:4896  20120727    PomBase 

Original comment by: mah11

**Comment by ValWood** [comment] 2018-02-14 19:30
I think this is an exact duplicate of 
https://github.com/pombase/pombase-chado/issues/536
too!

**Closed by ValWood** 2018-02-14 19:30 UTC
Labels: auto-migrated, external data, filtering, sourceforge
