### ISSUE TITLE
new interaction file to load

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#565] opened 2016-08-05 09:55 UTC
PMID:25795664 has some genetic interactions that have scores associated, and therefore fit BioGRID's "negative|positive genetic" evidence types. Because those (rightly) aren't available in Canto, I've put them in a file in BioGRID's format, and stuck it in a new subdirectory in pombe-embl/external:

pombe-embl/external_data/interactions/PMID_25795664_scored_interactions.tsv

I don't think there's any great rush, but it would be nice to get it loaded somewhere along the line. I'm working on Canto session approval for the paper, and I can follow up later to alert them whenever we add these annotations (i.e. approving the rest doesn't have to wait).

**Comment by ValWood** [comment] 2018-03-18 13:28
might be good to chat about this...on the list for this week.
how many annotations?

**Comment by mah11** [comment] 2018-03-19 12:05
% wc external_data/interactions/PMID_25795664_scored_interactions.tsv 
      79    1106    9785 external_data/interactions/PMID_25795664_scored_interactions.tsv

**Comment by ValWood** [comment] 2018-04-19 16:35
Kim should be able to load this.
Removing the "discuss" lable.

Kim let  us know if any questions.

**Comment by ValWood** [comment] 2018-05-31 11:12
try loading this...

**Comment by kimrutherford** [comment] 2018-06-12 04:38
I tried loading the new file and it didn't work out.

The current loader only supports the BioGRID download format:
 https://wiki.thebiogrid.org/doku.php/biogrid_tab_version_2.0

We'll need a new loader to support the BioGRID upload format.

**Comment by mah11** [comment] 2018-06-12 14:02
Drat. In the meantime, I can amend the existing file. Watch this space ...

**Comment by mah11** [comment] 2018-06-12 16:46
OK, I've added external_data/interactions/PMID_25795664_scored_interactions.tab2.txt ... hope it loads. I put "-" in a lot of the columns they say are for various IDs. Let me know if I should change anything.

**Comment by ValWood** [comment] 2018-06-28 10:04
did this work?

**Comment by kimrutherford** [comment] 2018-08-01 22:26
I've just added a header line and now it works.  I've added it to the nightly load and it should be visible on Friday morning.

**Comment by ValWood** [comment] 2018-08-07 18:07
Is this a duplicate of the ticket you closed earlier today?

**Comment by kimrutherford** [comment] 2018-08-07 20:46
It looks like the load didn't work.  There are 80 interactions in the file but a lot less than 80 interactions here:
  https://www.pombase.org/reference/PMID:25795664

I'll have a look at it.

**Comment by mah11** [comment] 2018-08-08 10:25
> It looks like the load didn't work. There are 80 interactions in the file but a lot less than 80 interactions here:
> https://www.pombase.org/reference/PMID:25795664

Yep, it looks like the pub page only shows the annotations done in Canto. Again, shout if I can/should do anything with the file. (Unassigning myself in the meantime, tho.)

**Comment by kimrutherford** [comment] 2018-08-13 21:37
I think this is fixed, possibly in time for tonight's load.  The file has PubMed IDs with a "PMID:" prefix rather than just a number.  The loader now copes with that.

**Comment by kimrutherford** [comment] 2018-08-16 01:35
Fixed!  There are now lots of interaction:
  https://www.pombase.org/reference/PMID:25795664

**Closed by kimrutherford** 2018-08-16 01:35 UTC
Labels: external data, needs testing, next
